sudo rm -rf web/.csslintrc
sudo rm -rf web/.eslintignore
sudo rm -rf web/.eslintrc.json
sudo rm -rf web/.ht.router.php
sudo rm -rf web/.htaccess
sudo rm -rf web/autoload.php
sudo rm -rf web/index.php
sudo rm -rf web/robots.txt
sudo rm -rf web/sites/development.services.yml
sudo rm -rf web/sites/example.settings.local.php
sudo rm -rf web/sites/example.sites.php
sudo rm -rf web/update.php
sudo rm -rf web/web.config
